In [16]:
import numpy as np 
#girdilerinin ağırlıklı toplamını hesaplar ve onu bir adım fonksiyonu ile eşler.
class Perceptron(object): #ilk değerler
    def __init__(self, input_size, lr=1, epochs=10):
        self.W = np.zeros(input_size+1)
        self.epochs = epochs
        self.lr = lr

    # aktivasyon işlemi uyguluyor
    def activation_fn(self, x):
        return 1 if x >=0 else 0

    # transpoze alır ve tek değer üretir bunu activasyona gonderir.
    def predict(self, x):
        x = np.insert(x, 0, 1)
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        #print(a)
        return a

    # verilen değerin transpozesini alıp istenen ağırlık değerleri olusturuyor. 
    def fit(self, X, d):  #d veri
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                y = self.predict(X[i])
                e = d[i] - y  #error değeri
                self.W = self.W + self.lr * e * np.insert(X[i], 0, 1)


In [17]:
mp = Perceptron(5)

In [18]:
mp.activation_fn(-10)

0

In [19]:
x = np.asarray([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [20]:
mp.predict(x)

1

In [21]:
X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

In [22]:
d = np.array([0,0,0,1])

In [23]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [24]:
perceptron = Perceptron(input_size=2)

In [25]:
perceptron.W

array([0., 0., 0.])

In [26]:
perceptron.fit(X,d)  #perceptron eğitildi

In [27]:
perceptron.W

array([-3.,  2.,  1.])

In [28]:
perceptron.predict(np.asarray([0,0]))

0

In [29]:
#2. soru xor için veriler
d = np.array([0, 1, 1, 0])
perceptron.fit(X,d)
perceptron.W

array([ 0., -1.,  0.])

In [30]:
d = np.array([1, 1, 1, 0]) #or
perceptron.fit(X,d)
perceptron.W

array([ 2., -2., -1.])

3. Soru 
imza verilerini binary şeklinde yani var ya da yok olarak ele alırsak 
[[0, 0, 0, ...,0, 0],
 [0, 0, 0, ...,0, 1],
 [0, 0, 0, ...,1, 0],
 ...
 [1, 1, 1, ..., 1, 1]] 
 şeklinde ilerleyen bir matris ortaya çıkar. 
 Bu durumdan dolayı X değerimiz:
 X = np.asarray([[0, 0, 0, ...,0, 0],
                 [0, 0, 0, ...,0, 1],
                 [0, 0, 0, ...,1, 0],
                 ...
                 [1, 1, 1, ..., 1, 1]] )
                 
d = np.array([0,0,0,1]) 
d'yi and kapısı olarak seçersek eğer her imza için farklı bir değer elde etme olasılığımız daha yüksek olur. 

4. Soru
Bu tür verilerde XOR sorun olabilir. Söyle ki, 
XOR işlevi doğrusal olarak ayrılabilir değildir.
Perceptron'da sadece 2 katman düğüm vardır (giriş düğümleri ve çıkış düğümleri). Giriş ve çıkış arasında 1 kat bağlantı olması nedeniyle genellikle tek katmanlı ağ olarak adlandırılır.
"Tek katmanlı" bir algılayıcı XOR'u uygulayamaz. Bunun nedeni, XOR'daki sınıfların doğrusal olarak ayrılabilir olmamasıdır. (0,0), (1,1) noktalarını (0,1), (1,0) noktalarından ayırmak için düz bir çizgi çizilemez. Çözüm olarak çok katmanlı ağlar kullanılabilir.